"use client";
import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import { DataProvider, useDataContext } from "@/context/dataContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Hamro Sano Ecommerce</title>
        <meta name="description" content="Generated by Srijan Karki" />
      </head>
      <body>
        <div className="layout">
          <Provider store={store}>
            <DataProvider>
              <Header />
              <main className="main">{children}</main>
              <Footer />
            </DataProvider>
          </Provider>
        </div>
      </body>
    </html>
  );
}
